name: "Run BDD Tests"

on:
  workflow_dispatch:
  pull_request:

jobs:

  run-bdd-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Maven and JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run bdd tests
      env:
        PROJETO_FIAP_CLUSTER_URL: ${{ env.PROJETO_FIAP_CLUSTER_URL }}
      run: mvn test

    - name: Check for tests failures
      run: |
        if grep -q '<error message=' target/surefire-reports/*.xml; then
          echo "Falha nos testes"
          exit 1
        fi
