name: "Run BDD Tests"

on:
  workflow_dispatch:
  pull_request:

jobs:

  run-bdd-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Maven and JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Retrieve Api Invoke URL
      run: |
        API_ID=$(aws apigateway get-rest-apis --query "items[?name=='${{ env.API_NAME }}'].id" --output text)
        INVOKE_URL="https://$API_ID.execute-api.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ env.STAGE_NAME }}/"

        echo "PROJETO_FIAP_CLUSTER_URL=$INVOKE_URL" >> $GITHUB_ENV

    - name: Run bdd tests
      env:
        PROJETO_FIAP_CLUSTER_URL: ${{ env.PROJETO_FIAP_CLUSTER_URL }}
      run: |
        echo "PROJETO_FIAP_CLUSTER_URL: $PROJETO_FIAP_CLUSTER_URL"
        mvn test

    - name: Check for tests failures
      run: |
        if grep -q '<error message=' target/surefire-reports/*.xml; then
          echo "Falha nos testes"
          exit 1
        fi
